import { Toaster as SonnarToaster } from '@/components/ui/sonner'
import { Toaster as UiToaster } from '@ui/toaster'
import type { Metadata, Viewport } from 'next'
import { Inter } from 'next/font/google'
import SessionWrapper from './_components/session-wrapper'
import './globals.css'

import { TooltipProvider } from '@/components/ui/tooltip'
import { ReactQueryProvider } from '@/services/react-queries/provider'
const inter = Inter({ subsets: ['latin'] })
export const metadata: Metadata = {
  title: 'Next + Auth Starter Kit',
  description: 'Generated by create next app',
  icons: {
    icon: '/assets/img/logos/favicon.svg'
  }
}
export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt_BR" className="dark">
      <head>
        <meta charSet="utf-8" />
      </head>
      <body className={inter.className}>
        <TooltipProvider>
          <ReactQueryProvider>
            <SessionWrapper>
              {children} <UiToaster /> <SonnarToaster />
            </SessionWrapper>
          </ReactQueryProvider>
        </TooltipProvider>
      </body>
    </html>
  )
}
